### ISSUE TITLE
Faulty Username Parsing...?

### ISSUE THREAD

**Issue by nathangiles** [ownaginatious/fbchat-archive-parser#46] opened 2017-07-01 20:48 UTC
First off thanks for this cool script.

Something seems to be wrong with the way you are parsing user names from the html. Not sure if facebook changed their html structure or if this something on my end or what.

I'm using the following command: 
```
fbcap messages.htm -d parsed_msgs/
```

And get the following output (I removed the FB ID #'s in XXXX@facebook.com):

```
Discovered chat thread with [XXXXXX@facebook.com, XXXXXXX@facebook.com]...Traceback (most recent call last):
  File "c:\program files (x86)\python\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python\Scripts\fbcap.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python\lib\site-packages\fbchat_archive_parser\main.py", line 188, in main
    app.run()
  File "c:\program files (x86)\python\lib\site-packages\clip.py", line 652, in run
    self.invoke(self.parse(tokens))
  File "c:\program files (x86)\python\lib\site-packages\clip.py", line 634, in invoke
    self._main.invoke(parsed)
  File "c:\program files (x86)\python\lib\site-packages\clip.py", line 519, in invoke
    self._callback(**{k: v for k, v in iteritems(parsed) if k not in self._subcommands})
  File "c:\program files (x86)\python\lib\site-packages\fbchat_archive_parser\main.py", line 125, in fbcap
    fbch = parser.parse()
  File "c:\program files (x86)\python\lib\site-packages\fbchat_archive_parser\parser.py", line 102, in parse
    self._parse_content()
  File "c:\program files (x86)\python\lib\site-packages\fbchat_archive_parser\parser.py", line 128, in _parse_content
    self._process_element(pos, element)
  File "c:\program files (x86)\python\lib\site-packages\fbchat_archive_parser\parser.py", line 262, in _process_element
    self.current_sender))
Exception: Data missing from message. This is a parsingerror: 2013-06-02 17:22:00-07:00, None
```

So obviously it's getting "None" for the username. If I just add the line self.current_user = "Unknown" before the thrown exception the script runs and completes but it obviously just results in every user  getting named "Unknown" in every conversation.

**Comment by ownaginatious** [comment] 2017-07-02 16:20
Hi there, thanks for pointing this out! What locale are you using on Facebook? I'll try pulling my own data again later and see if I can figure out the root cause of the issue.

**Comment by nathangiles** [comment] 2017-07-02 21:11
Not sure exactly what you mean by locale, but... "en_US"??

**Comment by ownaginatious** [comment] 2017-07-04 03:44
I meant the language locale you set your Facebook browsing settings too (most issues stem from other languages), but I was able to reproduce the problem anyway by just downloading my data again in English (US).

Anyway, you're right in that this issue was caused by a change on Facebook's end. Unfortunately, it doesn't seem to be a formatting change... the archives are now literally just missing the name of the user who posted each message :/

Example:

```html
...
    <div class="message">
        <div class="message_header"><span class="user"></span><span class="meta">Tuesday, February 12, 2013 at 9:15am PST</span></div>
    </div>
...
```

As you can see, the text is missing in `<span class="user"></span>`.

I'll try writing to Facebook to see if they can fix it.

Sorry for the inconvenience :/

**Comment by willium** [comment] 2017-07-09 03:27
Came to report same issue. Is it possible to get a fix to the tool in the short term that just doesn't store sender? Don't need it for my use case :)

**Comment by ownaginatious** [comment] 2017-07-09 04:13
Thanks for the suggestion; I fixed the parser so it prints a warning when the sender is absent and just replaces them with "Unknown" (version `0.9.post28`).

I also submitted a bug report to Facebook:

![image](https://user-images.githubusercontent.com/1163192/27991136-31e7784a-6422-11e7-8538-18d49abcae77.png)

Hopefully someone actually looks at it :/

Going to close this issue since there's nothing else that can be done on this end.

**Closed by ownaginatious** 2017-07-09 04:13 UTC

**Comment by willium** [comment] 2017-07-09 12:29
Did you a get bug report #? I can ask around.

**Comment by ownaginatious** [comment] 2017-07-09 16:39
Unfortunately, they didn't provide one and said they only really respond if they need more information.

**Comment by eldenvo** [comment] 2017-08-04 15:32
Don't suppose anyone has made any progress with facebook on this? Really irritating!

**Comment by ownaginatious** [comment] 2017-08-04 17:12
I haven't heard anything back yet, unfortunately. I was hoping it was fixed already, since I hadn't heard any new complaints :(

Not sure what else can be done, unless someone who works at or knows people who work at Facebook can give some insight.

**Comment by ownaginatious** [comment] 2017-08-09 18:29
@eldenvo @willium @nathangiles I just recently tried pulling a chat archive and it appears the missing name issue has been fixed on Facebook's end :)

**Comment by willium** [comment] 2017-08-09 18:30
Fantastic.

**Comment by eldenvo** [comment] 2017-08-11 06:40
Hmmm I also tried re-downloading my archive, and I've still got the same problem!

**Comment by ownaginatious** [comment] 2017-08-11 18:29
@eldenvo hmm, it seemed to work for me when I was downloading my data in Croatian (it was to fix a language specific problem for someone else). No idea if that was the reason it worked. You could try changing your Facebook locale and then downloading your data to that and see if it fixes it. It doesn't affect the actual output.

You have to wait at least a day after your last download request though, or else it will just give you your last download again. You also can't change your locale back until you get the email saying your download is ready.

![image](https://user-images.githubusercontent.com/1163192/29226754-0e39edb2-7e88-11e7-8029-6b498b792183.png)

**Comment by eldenvo** [comment] 2017-08-14 21:29
No, sadly I tried a different language and re-downloading, for the same problem!

Guess I'll just keep trying from time to time to see if FB fixes it!
