### ISSUE TITLE
CSV file output failing because of str vs. unicode

### ISSUE THREAD

**Issue by BunsenMcDubbs** [ownaginatious/fbchat-archive-parser#42] opened 2017-05-11 19:52 UTC
On Mac OS X Yosemite (10.10.5) with Python 2.7.10:

I get the following error when I try to output CSV's into separate files `fbcap -f csv -d <output dir> <input file>`. This happens with both my personal archive file and the sample test file.

```
Traceback (most recent call last):
  File "/Users/andrew/dev/auto-chat/venv/bin/fbcap", line 11, in <module>
    sys.exit(main())
  File "/Users/andrew/dev/auto-chat/venv/lib/python2.7/site-packages/fbchat_archive_parser/main.py", line 188, in main
    app.run()
  File "/Users/andrew/dev/auto-chat/venv/lib/python2.7/site-packages/clip.py", line 652, in run
    self.invoke(self.parse(tokens))
  File "/Users/andrew/dev/auto-chat/venv/lib/python2.7/site-packages/clip.py", line 634, in invoke
    self._main.invoke(parsed)
  File "/Users/andrew/dev/auto-chat/venv/lib/python2.7/site-packages/clip.py", line 519, in invoke
    self._callback(**{k: v for k, v in iteritems(parsed) if k not in self._subcommands})
  File "/Users/andrew/dev/auto-chat/venv/lib/python2.7/site-packages/fbchat_archive_parser/main.py", line 131, in fbcap
    write(format, fbch, directory or sys.stdout)
  File "/Users/andrew/dev/auto-chat/venv/lib/python2.7/site-packages/fbchat_archive_parser/writers/__init__.py", line 40, in write
    write_to_dir(selected_writer(), stream_or_dir, data)
  File "/Users/andrew/dev/auto-chat/venv/lib/python2.7/site-packages/fbchat_archive_parser/writers/__init__.py", line 68, in write_to_dir
    writer.write_thread(thread, stream=thread_file)
  File "/Users/andrew/dev/auto-chat/venv/lib/python2.7/site-packages/fbchat_archive_parser/writers/csv.py", line 56, in write_thread
    writer = self.get_writer(stream, True)
  File "/Users/andrew/dev/auto-chat/venv/lib/python2.7/site-packages/fbchat_archive_parser/writers/csv.py", line 45, in get_writer
    w.writeheader()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/csv.py", line 141, in writeheader
    self.writerow(header)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/csv.py", line 152, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
TypeError: must be unicode, not str
```

I did some hunting but could not find the root of the problem. I think it is something to do with `TextIOWrapper`'s UTF-8 encoding ([`writers/__init__.py:67-68`](https://github.com/ownaginatious/fbchat-archive-parser/blob/master/fbchat_archive_parser/writers/__init__.py#L67-L68)) and the `csv.py` library in Python 2?

**Comment by ownaginatious** [comment] 2017-05-12 01:17
Hey there, thanks for reporting this! You're right in that the issue is with the `TextIOWrapper`, which is configured in the writing-to-directory case to be in `UTF-8` mode. The solution is to extract the underlying byte-only stream and write to that instead. Python 2's CSV library can only work reliably with raw media files.

Fixed in version `0.9.post18`

**Closed by ownaginatious** 2017-05-12 01:17 UTC
