### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by friendswithsalad** [ownaginatious/fbchat-archive-parser#5] opened 2016-05-17 21:39 UTC
Hi, when I try to run the file I get the following error:
Traceback (most recent call last):
  File "/usr/local/bin/fbcap", line 9, in <module>
    load_entry_point('fbchat-archive-parser==0.6.post1', 'console_scripts', 'fbcap')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "build/bdist.macosx-10.11-intel/egg/fbchat_archive_parser/main.py", line 15, in <module>
AttributeError: 'module' object has no attribute 'App'

Would anyone be able to help? Thanks

**Comment by ownaginatious** [comment] 2016-05-17 21:44
Hi there, how are you trying to run the program? Did you install it through pip?

**Comment by friendswithsalad** [comment] 2016-05-17 21:57
My apologies, 
I rebuilt this in a virtualenv and python 3 and this error was fixed. However, I'm now getting a different error:

>   File "/Users/ericzhu/.virtualenvs/p3/bin/fbcap", line 11, in <module>
    sys.exit(main())
  File "/Users/ericzhu/.virtualenvs/p3/lib/python3.5/site-packages/fbchat_archive_parser/main.py", line 73, in main
    app.run()
  File "/Users/ericzhu/.virtualenvs/p3/lib/python3.5/site-packages/clip.py", line 652, in run
    self.invoke(self.parse(tokens))
  File "/Users/ericzhu/.virtualenvs/p3/lib/python3.5/site-packages/clip.py", line 634, in invoke
    self._main.invoke(parsed)
  File "/Users/ericzhu/.virtualenvs/p3/lib/python3.5/site-packages/clip.py", line 519, in invoke
    self._callback(**{k: v for k, v in iteritems(parsed) if k not in self._subcommands})
  File "/Users/ericzhu/.virtualenvs/p3/lib/python3.5/site-packages/fbchat_archive_parser/main.py", line 34, in fbcap
    progress_output=sys.stdout.isatty())
  File "/Users/ericzhu/.virtualenvs/p3/lib/python3.5/site-packages/fbchat_archive_parser/parser.py", line 98, in __init__
    self.__parse_content()
  File "/Users/ericzhu/.virtualenvs/p3/lib/python3.5/site-packages/fbchat_archive_parser/parser.py", line 123, in __parse_content
    self.__process_element(pos, element)
  File "/Users/ericzhu/.virtualenvs/p3/lib/python3.5/site-packages/fbchat_archive_parser/parser.py", line 297, in __process_element
    minutes=-1 * offset[1])
IndexError: list index out of range


>

**Comment by ownaginatious** [comment] 2016-05-17 22:06
Hmm, looks like it may be an issue with timezone formatting. I'm going to guess you're in a place with a timezone that doesn't have a minute offset and is formatted as `UTC-X` rather than `UTC-X:00`. I just submitted a new version to PyPI (0.6post2). Please let me know if that fixes it for you.

**Comment by friendswithsalad** [comment] 2016-05-17 22:38
The new version fixed this issue, thanks!
Yes, the timezone was formatted as follows: Thursday, December 19, 2014 at 10:20pm UTC+11

I'm now getting the same error as in #3 
Looking into my messages.htm file in Sublime Text shows that it's including ASCII Control characters as in [http://stackoverflow.com/questions/35800772/external-json-api-provides-unsanitized-character-dle-in-sublimetext-failing](url)
Looking into it at the moment.

**Comment by ownaginatious** [comment] 2016-05-17 22:46
Great, in that case I will close this issue and we can continue the conversation in #3. There should be a fallback parser that kicks in if the HTML in `messages.htm` is poorly formatted. The guy who opened #3 never confirmed whether that worked or not.

**Closed by ownaginatious** 2016-05-17 22:46 UTC
